name: CI - Automation Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: set up JDK
          uses: actions/setup-java@v3
          with:
                distribution: 'temurin'
                java-version: '17'

        - name: Grant excute permission for gradlew
          run: chmod +x gradlew

        - name: Run regression test
          run: ./gradlew regression

        - name: Run smoke test
          run: ./gradlew smoke

        - name: Upload test results
          uses: actions/upload-artifact@v3
          with:
              name: build-test-results
              path: target/

